-- MySQL Script generated by MySQL Workbench
-- Tue 07 Apr 2015 01:34:08 AM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sql377528
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sql377528` ;

-- -----------------------------------------------------
-- Schema sql377528
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql377528` DEFAULT CHARACTER SET latin1 ;
USE `sql377528` ;

-- -----------------------------------------------------
-- Table `sql377528`.`testDiaryTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql377528`.`testDiaryTable` ;

CREATE TABLE IF NOT EXISTS `sql377528`.`testDiaryTable` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1
COMMENT = 'Simple Diary Table for Testing';


-- -----------------------------------------------------
-- Table `sql377528`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql377528`.`User` ;

CREATE TABLE IF NOT EXISTS `sql377528`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `birth` DATE NULL,
  `idGeneralUser` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `idGeneralUser_UNIQUE` (`idGeneralUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql377528`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql377528`.`Category` ;

CREATE TABLE IF NOT EXISTS `sql377528`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `idUser` VARCHAR(45) NOT NULL,
  `idGeneralCategory` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`),
  INDEX `fk_Category_1_idx` (`idUser` ASC),
  UNIQUE INDEX `idGeneralCategory_UNIQUE` (`idGeneralCategory` ASC),
  CONSTRAINT `fk_Category_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sql377528`.`User` (`idGeneralUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sql377528`.`Diary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sql377528`.`Diary` ;

CREATE TABLE IF NOT EXISTS `sql377528`.`Diary` (
  `idDiary` INT NOT NULL AUTO_INCREMENT,
  `idCategory` VARCHAR(45) NULL,
  `idUser` VARCHAR(45) NOT NULL,
  `diaryText` LONGTEXT NULL,
  `dateTime` DATETIME NULL,
  `location` VARCHAR(100) NULL,
  `feeling` VARCHAR(45) NULL,
  `photoURL` VARCHAR(100) NULL,
  PRIMARY KEY (`idDiary`),
  INDEX `fk_Diary_1_idx` (`idUser` ASC),
  INDEX `fk_Diary_2_idx` (`idCategory` ASC),
  CONSTRAINT `fk_Diary_1`
    FOREIGN KEY (`idUser`)
    REFERENCES `sql377528`.`User` (`idGeneralUser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diary_2`
    FOREIGN KEY (`idCategory`)
    REFERENCES `sql377528`.`Category` (`idGeneralCategory`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
